server:
  application:
    name: financeiro
  port: 8082
  error:
    include-stacktrace: never

spring:
  kafka:
    bootstrap-servers: localhost:9093
  datasource:
    url: jdbc:postgresql://banco-financeiro:5432/financeiro
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: secret
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        boot:
          allow_jdbc_metadata_access: false
    generate-ddl: true

